import test from 'node:test';
import assert from 'node:assert/strict';
import { AppStateSchema, SnapshotSchema } from '../src/contracts/app.ts';
import { parseToolResult, toolOutputs } from '../src/contracts/tool-outputs.ts';
import { toolInputs } from '../src/contracts/tools.ts';
import { initialState,newRequest,snapshot } from '../src/server/app/state.ts';
import { runTool,confirmEvidence } from '../src/server/app/operations.ts';
const now='2026-09-23T06:00:00.000Z',user={userId:'contract-user',role:'client' as const};
function prepared(){const state=initialState(now);newRequest(state,user,'slotpilot-contract');runTool(state,user,'update_request',{expectedRequestVersion:1,patch:{serviceIds:['oil-change'],vehicleId:'sedan-petrol',allowedDates:['2026-09-24']}},now);runTool(state,user,'find_options',{expectedRequestVersion:2},now);const r=snapshot(state,user).request!;runTool(state,user,'prepare_booking',{expectedRequestVersion:2,optionId:r.options[0].optionId},now);return state}
test('canonical persistence and snapshot schemas accept real prepared and committed flows',()=>{const state=prepared();assert.deepEqual(AppStateSchema.parse(state),state);const action=snapshot(state,user).request!.preparedAction!;const ev=confirmEvidence(state,user,now,{actionId:action.actionId,source:'button'});runTool(state,user,'confirm_booking',{actionId:action.actionId,confirmationRef:ev.confirmationRef},now);const restored=AppStateSchema.parse(JSON.parse(JSON.stringify(state)));assert.equal(Object.keys(restored.bookings).length,1);assert.deepEqual(SnapshotSchema.parse(snapshot(restored,user)),snapshot(restored,user))});
test('persistence rejects invalid booking version and forged canonical action fields',()=>{const state=prepared();const a=Object.values(state.actions)[0];assert.throws(()=>AppStateSchema.parse({...state,actions:{[a.actionId]:{...a,requestVersion:0}}}));assert.throws(()=>AppStateSchema.parse({...state,actions:{[a.actionId]:{...a,confirmed:true}}}));assert.throws(()=>AppStateSchema.parse({...state,schemaVersion:2}))});
test('record and cached-result validators reject prototype keys and non-JSON data',()=>{const state=initialState(now);assert.throws(()=>AppStateSchema.parse({...state,bookings:JSON.parse('{"__proto__":{}}')}));assert.throws(()=>AppStateSchema.parse({...state,sessions:{user:{requestId:null,tokenTimes:[],toolCalls:{call:{signature:'x',result:()=>true}}}}}))});
test('each advertised tool has a strict output contract',()=>{assert.deepEqual(Object.keys(toolOutputs).sort(),Object.keys(toolInputs).sort());assert.throws(()=>parseToolResult('confirm_booking',{success:true,bookingId:'imagined'}));assert.throws(()=>parseToolResult('get_booking',{status:'not_committed',actionId:'a',canRetry:'yes'}));assert.deepEqual(parseToolResult('get_booking',{status:'not_committed',actionId:'a',canRetry:false}),{status:'not_committed',actionId:'a',canRetry:false})});
