// Explicit mocked provider/audio. These tests do not validate live AssemblyAI or audible latency.
import test from 'node:test';
import assert from 'node:assert/strict';
import { VoiceController, api } from '../src/features/voice/controller.mjs';
import { BrowserAudio } from '../src/features/voice/audio.mjs';
import { voiceToolPayload } from '../src/features/voice/tool-payload.mjs';
test('voice payload preserves exact business results and version without duplicate UI history',()=>{const data={actionId:'action',snapshot:{totalPriceKzt:23000,startAt:'2026-09-25T04:00:00Z'},confirmation:'Read every detail and ask for confirmation'};const response={ok:true,data,bookings:[{bookingId:'saved',bookingVersion:2,status:'confirmed',snapshot:data.snapshot,ownerId:'owner'}],request:{requestId:'request',requestVersion:7,constraints:{vehicleId:'sedan-petrol'},stage:'awaiting_confirmation'},events:Array(100).fill({type:'old-event'}),search:{options:Array(10).fill(data)}};const compact=voiceToolPayload(response);assert.deepEqual(compact.data,data);assert.deepEqual(compact.bookings,[{bookingId:'saved',bookingVersion:2,status:'confirmed',snapshot:data.snapshot}]);assert.equal(compact.currentRequest.requestVersion,7);assert.ok(JSON.stringify(compact).length<JSON.stringify(response).length/2);assert.deepEqual(voiceToolPayload({ok:false,error:{code:'STALE_REQUEST'}}).error,{code:'STALE_REQUEST'})});
const tick=()=>new Promise(r=>setImmediate(r));
test('mock: late tool interruption drops only that call and leaves new speech playing',async()=>{let release;const h=await harness(async()=>new Promise(r=>{release=r}));try{h.ws.receive({type:'reply.started',reply_id:'fc-old'});h.ws.receive({type:'tool.call',call_id:'old',name:'find_options',arguments:{}});await tick();h.ws.receive({type:'reply.started',reply_id:'new'});h.ws.receive({type:'reply.audio',data:'new'});h.ws.receive({type:'reply.done',reply_id:'fc-old',status:'interrupted'});release({ok:true});await tick();h.ws.receive({type:'reply.done',reply_id:'new',status:'completed'});assert.equal(h.stats().cleared,0);assert.equal(h.sent.filter(e=>e.type==='tool.result').length,0)}finally{await h.close()}});
test('mock: callbacks from a stopped connection cannot affect its replacement',async()=>{const h=await harness(async()=>({ok:true}));try{const oldSocket=h.ws,oldAudio=h.c.audio;await h.c.stop();await h.c.start();h.c.socket.receive({type:'session.ready'});const before=h.sent.length;oldAudio.onCapture(new Int16Array(480).buffer);oldSocket.onerror?.();oldSocket.receive({type:'reply.done',status:'interrupted'});assert.equal(h.c.active,true);assert.equal(h.sent.length,before)}finally{await h.close()}});
test('mock: reply.done before tool.call sends the result without another provider event',async()=>{const h=await harness(async()=>({ok:true,data:{options:[]}}));try{h.ws.receive({type:'reply.started',reply_id:'fc-early'});h.ws.receive({type:'reply.done',reply_id:'fc-early',status:'completed'});h.ws.receive({type:'tool.call',call_id:'early',name:'find_options',arguments:{expectedRequestVersion:1}});await tick();assert.equal(h.sent.filter(e=>e.type==='tool.result').length,1)}finally{await h.close()}});
test('mock: malformed tool arguments return an error result instead of hanging',async()=>{let calls=0;const h=await harness(async()=>{calls++;return {ok:true}});try{h.ws.receive({type:'tool.call',call_id:'invalid',name:'update_request',arguments:'{broken'});h.ws.receive({type:'reply.done',reply_id:'fc-invalid',status:'completed'});await tick();const result=h.sent.find(e=>e.type==='tool.result');assert.equal(result?.is_error,true);assert.equal(calls,0)}finally{await h.close()}});
test('mock: late interruption and audio from an older reply cannot cut a newer reply',async()=>{const h=await harness(async()=>({ok:true}));try{h.ws.receive({type:'reply.started',reply_id:'old'});h.ws.receive({type:'reply.started',reply_id:'new'});h.ws.receive({type:'reply.audio',reply_id:'old',data:'old'});h.ws.receive({type:'reply.done',reply_id:'old',status:'interrupted'});h.ws.receive({type:'reply.audio',data:'current audio without optional reply ID'});assert.equal(h.stats().cleared,0);assert.equal(h.stats().played,1)}finally{await h.close()}});
test('voice requests have a deadline and report an expired request',async()=>{const previous=globalThis.fetch;let signal;try{globalThis.fetch=async(_path,options)=>{signal=options.signal;throw new DOMException('expired','TimeoutError')};await assert.rejects(api('/api/tools',{}),error=>error.code==='REQUEST_TIMEOUT');assert.ok(signal,'voice request must carry an abort signal')}finally{globalThis.fetch=previous}});
async function harness(execute){const previous={fetch:globalThis.fetch,WebSocket:globalThis.WebSocket,open:BrowserAudio.prototype.open,close:BrowserAudio.prototype.close,clear:BrowserAudio.prototype.clear,play:BrowserAudio.prototype.play};let played=0,cleared=0,updated=0;const sent=[];
 BrowserAudio.prototype.open=async()=>({});BrowserAudio.prototype.close=async()=>{};BrowserAudio.prototype.clear=function(){cleared++};BrowserAudio.prototype.play=function(){played++};
 class WS{constructor(){this.readyState=1;this.bufferedAmount=0;WS.instance=this;queueMicrotask(()=>this.onopen?.())}send(raw){const e=JSON.parse(raw);sent.push(e);if(e.type==='session.end')queueMicrotask(()=>this.listener?.({data:JSON.stringify({type:'session.ended'})}))}close(){this.readyState=3;this.onclose?.()}addEventListener(name,fn){if(name==='message')this.listener=fn}receive(e){this.onmessage?.({data:JSON.stringify(e)})}}
 globalThis.WebSocket=WS;globalThis.fetch=async(path,init)=>{if(path==='/api/voice/token')return Response.json({token:'mock-token',websocketUrl:'wss://agents.assemblyai.com/v1/ws',maxSessionSeconds:300,session:{system_prompt:'Original safeguards'}});if(path==='/api/evidence')return Response.json({confirmationRef:'evidence-1'});if(path==='/api/tools')return Response.json(await execute(JSON.parse(init.body)));throw new Error('Unexpected mock request')};
 const state={request:{requestId:'r1',requestVersion:1,constraints:{},preparedAction:{actionId:'a1'}}};const c=new VoiceController({snapshot:()=>state,updateSnapshot:()=>updated++,reconcile:async()=>{},state:()=>{},error:()=>{}});await c.start();WS.instance.receive({type:'session.ready'});return {c,ws:WS.instance,sent,stats:()=>({played,cleared,updated}),close:async()=>{await c.stop();await tick();Object.assign(globalThis,{fetch:previous.fetch,WebSocket:previous.WebSocket});Object.assign(BrowserAudio.prototype,{open:previous.open,close:previous.close,clear:previous.clear,play:previous.play})}}}
test('mock: a backchannel leaves the answer audible; a confirmed interruption clears old audio',async()=>{const h=await harness(async()=>({ok:true}));try{h.ws.receive({type:'reply.started',reply_id:'old'});h.ws.receive({type:'reply.audio',reply_id:'old',data:'mock'});h.ws.receive({type:'input.speech.started'});h.ws.receive({type:'reply.audio',reply_id:'old',data:'more'});assert.equal(h.stats().played,2);assert.equal(h.stats().cleared,0);h.ws.receive({type:'reply.done',reply_id:'old',status:'interrupted'});assert.equal(h.stats().cleared,1);h.ws.receive({type:'reply.audio',reply_id:'old',data:'stale'});h.ws.receive({type:'reply.started',reply_id:'new'});h.ws.receive({type:'reply.audio',reply_id:'old',data:'stale'});h.ws.receive({type:'reply.audio',reply_id:'new',data:'new'});assert.equal(h.stats().played,3)}finally{await h.close()}});
test('mock: loud microphone input cannot falsely cut agent speech',async()=>{const h=await harness(async()=>({ok:true}));try{h.ws.receive({type:'reply.started',reply_id:'old'});h.ws.receive({type:'reply.audio',reply_id:'old',data:'mock'});for(let i=0;i<5;i++)h.c.audio.onCapture(new Int16Array(480).fill(5000).buffer);assert.equal(h.stats().cleared,0);h.ws.receive({type:'reply.audio',reply_id:'old',data:'more'});assert.equal(h.stats().played,2)}finally{await h.close()}});
test('mock: tool results wait for their own reply.done and retain original call ID',async()=>{const h=await harness(async()=>({ok:true,data:{value:1}}));try{h.ws.receive({type:'reply.started',reply_id:'a'});h.ws.receive({type:'tool.call',call_id:'call-a',name:'find_options',arguments:{expectedRequestVersion:1}});await tick();assert.equal(h.sent.filter(e=>e.type==='tool.result').length,0);h.ws.receive({type:'reply.done',reply_id:'a',status:'completed'});assert.equal(h.sent.filter(e=>e.type==='tool.result').length,0);h.ws.receive({type:'reply.done',reply_id:'fc-call-a',status:'completed'});assert.equal(h.sent.find(e=>e.type==='tool.result').call_id,'call-a')}finally{await h.close()}});
test('mock: a reply with text but no audio reports the failure instead of silently continuing',async()=>{const h=await harness(async()=>({ok:true}));let error='';h.c.c.error=e=>{error=e};try{h.ws.receive({type:'reply.started',reply_id:'silent'});h.ws.receive({type:'transcript.agent',reply_id:'silent',item_id:'silent-item',text:'I can help.'});h.ws.receive({type:'reply.done',reply_id:'silent',status:'completed'});assert.match(error,/text without audio/);assert.equal(h.c.active,false)}finally{await h.close()}});
test('mock: an interrupted in-flight write still updates saved UI state and does not speak stale result',async()=>{let release;const gate=new Promise(r=>release=r);const h=await harness(async()=>{await gate;return {ok:true,data:{bookingId:'saved'}}});try{h.ws.receive({type:'tool.call',call_id:'write-1',name:'confirm_booking',arguments:{actionId:'a1'}});await tick();h.ws.receive({type:'input.speech.started'});release();await tick();await tick();assert.equal(h.stats().updated,1);h.ws.receive({type:'reply.done',status:'completed'});assert.equal(h.sent.filter(e=>e.type==='tool.result').length,0)}finally{await h.close()}});
test('mock: failed write checks its action ID without blocking a later tool call',async()=>{const calls=[];const h=await harness(async input=>{calls.push(input);if(input.name==='confirm_booking')throw new SyntaxError('invalid server response');return {ok:true,request:{requestId:'r1'},data:{status:'not_committed'}}});try{h.ws.receive({type:'tool.call',call_id:'write-failed',name:'confirm_booking',arguments:{actionId:'a1'}});await tick();await tick();assert.equal(calls[1].name,'get_booking');assert.equal(calls[1].arguments.actionId,'a1');h.ws.receive({type:'reply.done',reply_id:'fc-write-failed',status:'completed'});assert.equal(JSON.parse(h.sent.find(e=>e.type==='tool.result').result).error.code,'CONNECTION_ERROR');h.ws.receive({type:'tool.call',call_id:'read-next',name:'find_options',arguments:{expectedRequestVersion:1}});await tick();assert.equal(calls[2].name,'find_options')}finally{await h.close()}});
test('mock: partial user transcript cannot generate confirmation evidence',async()=>{const h=await harness(async()=>({ok:true}));try{h.ws.receive({type:'transcript.user.delta',item_id:'utterance',text:'Yes'});await tick();assert.equal(h.c.confirmationRef,null);h.ws.receive({type:'transcript.user',item_id:'utterance',text:'Yes'});await tick();assert.equal(h.c.confirmationRef,'evidence-1')}finally{await h.close()}});
test('mock: manual sync retains the base safety prompt',async()=>{const h=await harness(async()=>({ok:true}));try{h.c.sync();const updates=h.sent.filter(e=>e.type==='session.update');assert.match(updates.at(-1).session.system_prompt,/Original safeguards/);assert.match(updates.at(-1).session.system_prompt,/CURRENT AUTHORITATIVE STATE/)}finally{await h.close()}});
