import test from 'node:test';
import assert from 'node:assert/strict';
import { initialState,newRequest,snapshot,dataset } from '../src/server/app/state.ts';
import { runTool,confirmEvidence,executeAction,demoAction,idempotentTool,invalidateVoiceEvidence } from '../src/server/app/operations.ts';
import type { Action,User,AppState,Booking } from '../src/contracts/app.ts';
const now='2026-09-23T06:00:00.000Z';const user:User={userId:'u1',role:'client'};const admin:User={userId:'a1',role:'admin'};
const patch={serviceIds:['oil-change'],vehicleId:'sedan-petrol',allowedDates:['2026-09-24'],allowedBranchIds:['centre'],arrivalNotBefore:'14:00',maxBudgetKzt:40000};
function ready(s=initialState(now),u=user){const r=newRequest(s,u,'slotpilot-test');const out=runTool(s,u,'update_request',{patch,expectedRequestVersion:r.requestVersion},now) as any;if(!out.search)runTool(s,u,'find_options',{expectedRequestVersion:snapshot(s,u).request!.requestVersion},now);return s}
function prepared(s:AppState,u=user){const r=snapshot(s,u).request!;return runTool(s,u,'prepare_booking',{optionId:r.options[0].optionId,expectedRequestVersion:r.requestVersion},now) as Action}
function evidence(s:AppState,a:Action,u=user){return confirmEvidence(s,u,now,{source:'button',actionId:a.actionId}).confirmationRef!}
function book(s:AppState,u=user){const a=prepared(s,u);const ref=evidence(s,a,u);return {a,ref,b:executeAction(s,u,now,a.actionId,ref,'create')}}
function code(fn:()=>unknown,expected:string){assert.throws(fn,(e:any)=>e.code===expected)}
test('a complete update returns fresh matching options in the same tool call',()=>{const s=initialState(now),r=newRequest(s,user,'slotpilot-test');const out=runTool(s,user,'update_request',{patch,expectedRequestVersion:r.requestVersion},now) as any;assert.equal(out.missingFields.length,0);assert.equal(out.search.status,'ok');assert.ok(out.search.options.length);assert.equal(out.search.sourceStateRevision,out.request.stateRevision);assert.deepEqual(snapshot(s,user).search,out.search)});
test('confirmed visit reserves both resources for entire visit and survives JSON state serialization',()=>{const s=ready();const {b}=book(s);assert.equal(b.status,'confirmed');const r=dataset(s,now).reservations.filter(r=>r.id.startsWith(b.bookingId));assert.equal(r.length,2);assert.equal(r[0].endAt,b.snapshot.readyAt);const restored=JSON.parse(JSON.stringify(s));assert.equal(snapshot(restored,user).bookings[0].bookingId,b.bookingId)});
test('repeated confirmation with new transport call returns same saved booking after expiry',()=>{const s=ready();const {a,ref,b}=book(s);const repeat=runTool(s,user,'confirm_booking',{actionId:a.actionId,confirmationRef:ref},'2026-09-23T10:00:00.000Z') as Booking;assert.equal(repeat.bookingId,b.bookingId);assert.equal(Object.keys(s.bookings).length,1)});
test('new conditions invalidate an old prepared proposal and its consent',()=>{const s=ready();const a=prepared(s),ref=evidence(s,a);runTool(s,user,'update_request',{patch:{maxBudgetKzt:30000},expectedRequestVersion:snapshot(s,user).request!.requestVersion},now);code(()=>executeAction(s,user,now,a.actionId,ref,'create'),'STALE_REQUEST');assert.equal(Object.keys(s.bookings).length,0)});
test('changing conditions preserves dates and budget',()=>{const s=ready();runTool(s,user,'update_request',{patch:{addServiceIds:['brake-check','diagnostics'],readyNoLaterThan:'16:00'},expectedRequestVersion:snapshot(s,user).request!.requestVersion},now);const r=snapshot(s,user).request!;assert.equal(r.constraints.maxBudgetKzt,40000);assert.deepEqual(r.constraints.allowedDates,['2026-09-24']);const out=runTool(s,user,'find_options',{expectedRequestVersion:r.requestVersion},now) as any;assert.equal(out.options.length,0);assert.ok(out.relaxations.some((x:any)=>x.preview.branchId==='north'));assert.equal(s.comparisons[r.requestId].totalDurationMinutes,120)});
test('yes but add diagnostics is not confirmation evidence',()=>{const s=ready();const a=prepared(s);const e=confirmEvidence(s,user,now,{actionId:a.actionId,source:'voice',text:'Yes, but add diagnostics.',itemId:'final-1'});assert.equal(e.confirmationRef,null);assert.equal(Object.keys(s.evidence).length,0)});
test('final affirmative voice evidence is tied to exact prepared action',()=>{const s=ready();const a=prepared(s);const e=confirmEvidence(s,user,now,{actionId:a.actionId,source:'voice',text:'Yes, book it.',itemId:'final-2'});assert.ok(e.confirmationRef);assert.equal(executeAction(s,user,now,a.actionId,e.confirmationRef!,'create').status,'confirmed')});
test('new speech invalidates unexecuted voice evidence',()=>{const s=ready();const a=prepared(s);const e=confirmEvidence(s,user,now,{actionId:a.actionId,source:'voice',text:'Yes.',itemId:'final-3'});invalidateVoiceEvidence(s,user);code(()=>executeAction(s,user,now,a.actionId,e.confirmationRef!,'create'),'CONFIRMATION_REQUIRED')});
test('interrupting after commit does not discard saved result',()=>{const s=ready();const {a,ref,b}=book(s);invalidateVoiceEvidence(s,user);assert.equal(executeAction(s,user,now,a.actionId,ref,'create').bookingId,b.bookingId)});
test('preparation does not reserve resources',()=>{const s=ready();const before=dataset(s,now).reservations.length;prepared(s);assert.equal(dataset(s,now).reservations.length,before)});
test('conflict after preparation prevents booking and does not create a record',()=>{const s=ready();const a=prepared(s),ref=evidence(s,a);demoAction(s,admin,now,'occupy',a.snapshot.optionId);code(()=>executeAction(s,user,now,a.actionId,ref,'create'),'SLOT_CONFLICT');assert.equal(Object.keys(s.bookings).length,0)});
test('two users choosing the same resource cannot both commit against latest state',()=>{const s=ready(),a1=prepared(s),ref1=evidence(s,a1),u2:User={userId:'u2',role:'client'};ready(s,u2);const a2=prepared(s,u2),ref2=evidence(s,a2,u2);executeAction(s,user,now,a1.actionId,ref1,'create');code(()=>executeAction(s,u2,now,a2.actionId,ref2,'create'),'SLOT_CONFLICT');assert.equal(Object.keys(s.bookings).length,1)});
test('foreign booking and foreign action are denied',()=>{const s=ready();const {a,ref,b}=book(s);const u2:User={userId:'u2',role:'client'};ready(s,u2);code(()=>runTool(s,u2,'get_booking',{bookingId:b.bookingId},now),'NOT_AUTHORIZED');code(()=>executeAction(s,u2,now,a.actionId,ref,'create'),'NOT_AUTHORIZED')});
test('expired action cannot commit',()=>{const s=ready();const a=prepared(s),ref=evidence(s,a);code(()=>executeAction(s,user,'2026-09-23T06:03:00.000Z',a.actionId,ref,'create'),'OPTION_EXPIRED')});
test('a model-provided boolean cannot serve as confirmation',()=>{const s=ready();const a=prepared(s);assert.throws(()=>runTool(s,user,'confirm_booking',{actionId:a.actionId,confirmed:true},now));code(()=>executeAction(s,user,now,a.actionId,'invented','create'),'CONFIRMATION_REQUIRED')});
test('transport idempotency rejects a reused call ID with changed arguments',()=>{const s=ready();idempotentTool(s,user,'call-1','get_services',{},now);code(()=>idempotentTool(s,user,'call-1','get_services',{vehicleId:'ev-demo'},now),'VALIDATION_ERROR')});
test('cancel prepares first, then releases both resources, repeated cancel is idempotent',()=>{const s=ready();const {b}=book(s);const a=runTool(s,user,'prepare_change',{changeType:'cancel',bookingId:b.bookingId,expectedBookingVersion:1},now) as Action;assert.equal(s.bookings[b.bookingId].status,'confirmed');const ref=evidence(s,a);const cancelled=executeAction(s,user,now,a.actionId,ref,'cancel');assert.equal(cancelled.bookingVersion,2);assert.equal(dataset(s,now).reservations.filter(r=>r.id.startsWith(b.bookingId)).length,0);assert.equal(executeAction(s,user,now,a.actionId,ref,'cancel').bookingVersion,2)});
test('failed reschedule preserves original booking and its reservations',()=>{const s=ready();const {b}=book(s);const old=structuredClone(b);ready(s);const r=snapshot(s,user).request!;const a=runTool(s,user,'prepare_change',{changeType:'reschedule',bookingId:b.bookingId,expectedBookingVersion:1,optionId:r.options[0].optionId,expectedRequestVersion:r.requestVersion},now) as Action;const ref=evidence(s,a);demoAction(s,admin,now,'occupy',a.snapshot.optionId);code(()=>executeAction(s,user,now,a.actionId,ref,'reschedule'),'SLOT_CONFLICT');assert.deepEqual(s.bookings[b.bookingId],old);assert.equal(dataset(s,now).reservations.filter(r=>r.id.startsWith(b.bookingId)).length,2)});
test('successful reschedule keeps booking ID and increments version',()=>{const s=ready();const {b}=book(s);const oldStart=b.snapshot.startAt;ready(s);const r=snapshot(s,user).request!;const a=runTool(s,user,'prepare_change',{changeType:'reschedule',bookingId:b.bookingId,expectedBookingVersion:1,optionId:r.options[0].optionId,expectedRequestVersion:r.requestVersion},now) as Action;const result=executeAction(s,user,now,a.actionId,evidence(s,a),'reschedule');assert.equal(result.bookingId,b.bookingId);assert.equal(result.bookingVersion,2);assert.notEqual(result.snapshot.startAt,oldStart);assert.equal(Object.keys(s.bookings).length,1)});
test('demo reset invalidates old actions without mutating another state namespace',()=>{const s=ready(),other=ready();const a=prepared(s),ref=evidence(s,a),oldGeneration=s.generation;const before=JSON.stringify(other);demoAction(s,admin,now,'reset');assert.notEqual(s.generation,oldGeneration);code(()=>executeAction(s,user,now,a.actionId,ref,'create'),'NOT_AUTHORIZED');assert.equal(JSON.stringify(other),before)});
test('client cannot reset or occupy demo resources',()=>{const s=ready();code(()=>demoAction(s,user,now,'reset'),'NOT_AUTHORIZED');code(()=>demoAction(s,user,now,'occupy',snapshot(s,user).request!.options[0].optionId),'NOT_AUTHORIZED')});
test('part availability is checked both on search and after preparation',()=>{const s=ready();const a=prepared(s),ref=evidence(s,a);demoAction(s,admin,now,'part');code(()=>executeAction(s,user,now,a.actionId,ref,'create'),'PART_UNAVAILABLE');const result=runTool(s,user,'find_options',{expectedRequestVersion:snapshot(s,user).request!.requestVersion},now) as any;assert.equal(result.options.length,0);assert.ok(result.reasons.some((x:any)=>x.code==='PART_UNAVAILABLE'));assert.ok(result.relaxations.some((x:any)=>x.preview.branchId==='north'))});
test('callback is stored once for the same request and reason',()=>{const s=ready();const args={reason:'Unusual engine noise',expectedRequestVersion:snapshot(s,user).request!.requestVersion};runTool(s,user,'create_callback_request',args,now);runTool(s,user,'create_callback_request',args,now);assert.equal(Object.keys(s.callbacks).length,1)});
