import { AppError, rateLimit } from './db.ts';
import type { User } from '../../contracts/app.ts';
const encoder=new TextEncoder(),cookieName='slotpilot_account';
// Browser-safe public key for the existing demo project. Never use a service key here.
const demoPublishableKey='sb_publishable_-rt9Ylj2doGXvQKLt7-Vzw_Zxm_kKlS';
function publishableKey(){return process.env.SUPABASE_PUBLISHABLE_KEY||(process.env.SUPABASE_URL?.includes('lylcxxdrpralrstxzuct.supabase.co')?demoPublishableKey:'')}
export function authConfigured(){return Boolean(process.env.SUPABASE_URL&&(process.env.SESSION_SECRET?.length??0)>=32&&publishableKey())}
async function sign(s:string){const secret=process.env.SESSION_SECRET;if(!secret||secret.length<32)throw new AppError('SETUP_REQUIRED','The server session secret is not configured.',503);const key=await crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return Buffer.from(await crypto.subtle.sign('HMAC',key,encoder.encode(s))).toString('base64url')}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');if(!origin||origin!==new URL(req.url).origin)throw new AppError('NOT_AUTHORIZED','Use this application to perform the action.',403)}
async function equal(a:string,b:string){const x=new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(a)));const y=new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(b)));let n=0;for(let i=0;i<x.length;i++)n|=x[i]^y[i];return n===0}
async function authRequest(path:string,payload:unknown,token?:string){const url=process.env.SUPABASE_URL,key=publishableKey();if(!url||!key)throw new AppError('SETUP_REQUIRED','Supabase Auth is not configured.',503);let response:Response;try{response=await fetch(`${url.replace(/\/$/,'')}/auth/v1/${path}`,{method:token?'PUT':'POST',headers:{apikey:key,'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify(payload),cache:'no-store',signal:AbortSignal.timeout(10000)})}catch{throw new AppError('PROVIDER_UNREACHABLE','Authentication is temporarily unavailable. Please try again.',503)}
 const data=await response.json().catch(()=>({}));if(!response.ok){if(response.status===429)throw new AppError('RATE_LIMIT','Too many requests. Please try again later.',429);throw new AppError('NOT_AUTHORIZED',path.startsWith('token')?'Incorrect email or password, or email not yet confirmed.':'Could not complete account request. Check your details or try again later.',400)}return data as {access_token?:string;user?:{id:string;app_metadata?:{role?:string}}}}
async function sessionCookie(req:Request,user:User){const body=Buffer.from(JSON.stringify({...user,exp:Date.now()+86400000})).toString('base64url');return `${cookieName}=${body}.${await sign(body)}; HttpOnly; SameSite=Strict; Path=/; Max-Age=86400${new URL(req.url).protocol==='https:'?'; Secure':''}`}
export async function currentUser(req:Request):Promise<User|null>{try{const token=req.headers.get('cookie')?.split(';').map(c=>c.trim()).find(c=>c.startsWith(`${cookieName}=`))?.slice(cookieName.length+1);if(!token)return null;const [body,mac]=token.split('.');if(!body||!mac||!await equal(mac,await sign(body)))return null;const data=JSON.parse(Buffer.from(body,'base64url').toString());if(data.exp<Date.now()||!['client','admin'].includes(data.role)||typeof data.userId!=='string')return null;return {userId:data.userId,role:data.role}}catch{return null}}
export async function requireUser(req:Request){const user=await currentUser(req);if(!user)throw new AppError('NOT_AUTHORIZED','Sign in to save a booking.',401);return user}
export function requireAdmin(user:User){if(user.role!=='admin')throw new AppError('NOT_AUTHORIZED','Administrator access is required.',403)}
export async function login(req:Request,email:string,password:string){sameOrigin(req);await rateLimit('login-global',60,600);const result=await authRequest('token?grant_type=password',{email,password});if(!result.user?.id||!result.access_token)throw new AppError('NOT_AUTHORIZED','Confirm your email, then sign in.',401);const user:User={userId:result.user.id,role:result.user.app_metadata?.role==='admin'?'admin':'client'};return {user,cookie:await sessionCookie(req,user)}}
export async function signUp(req:Request,email:string,password:string){sameOrigin(req);await rateLimit('signup-global',30,3600);await authRequest('signup',{email,password});return {message:'Check your email to confirm the account, then sign in.'}}
export async function recover(req:Request,email:string){sameOrigin(req);await rateLimit('recover-global',20,3600);try{await authRequest(`recover?redirect_to=${encodeURIComponent(new URL(req.url).origin+'/')}`,{email})}catch(e){if(!(e instanceof AppError)||e.code!=='NOT_AUTHORIZED')throw e}return {message:'If this address has an account, a password reset email is on its way.'}}
export async function resetPassword(req:Request,accessToken:string,password:string){sameOrigin(req);await authRequest('user',{password},accessToken);return {message:'Password updated. Please sign in.'}}
