import { AppError, rateLimit } from './db.ts';
import type { User } from '../../contracts/app.ts';
const encoder=new TextEncoder();
async function sign(s:string){const secret=process.env.SESSION_SECRET;if(!secret||secret.length<32)throw new AppError('SETUP_REQUIRED','The server session secret is not configured.',503);const key=await crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return Buffer.from(await crypto.subtle.sign('HMAC',key,encoder.encode(s))).toString('base64url')}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');if(!origin||origin!==new URL(req.url).origin)throw new AppError('NOT_AUTHORIZED','Use this application to perform the action.',403)}
async function equal(a:string,b:string){const x=new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(a)));const y=new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(b)));let n=0;for(let i=0;i<x.length;i++)n|=x[i]^y[i];return n===0}
export async function currentUser(req:Request):Promise<User|null>{try{const token=req.headers.get('cookie')?.split(';').map(c=>c.trim()).find(c=>c.startsWith('slotpilot_session='))?.slice(18);if(!token)return null;const [body,mac]=token.split('.');if(!body||!mac||!await equal(mac,await sign(body)))return null;const data=JSON.parse(Buffer.from(body,'base64url').toString());if(data.exp<Date.now()||!['client','admin'].includes(data.role)||typeof data.userId!=='string')return null;return {userId:data.userId,role:data.role}}catch{return null}}
export async function requireUser(req:Request){const user=await currentUser(req);if(!user)throw new AppError('NOT_AUTHORIZED','Sign in to save a booking.',401);return user}
export function requireAdmin(user:User){if(user.role!=='admin')throw new AppError('NOT_AUTHORIZED','Administrator access is required.',403)}
export async function login(req:Request,role:'client'|'admin',password:string){sameOrigin(req);await rateLimit('login-global',60,600);await rateLimit(`login-${role}`,30,600);const expected=process.env[role==='admin'?'DEMO_ADMIN_PASSWORD':'DEMO_CLIENT_PASSWORD'];if(!expected||expected.length<12)throw new AppError('SETUP_REQUIRED','Demo passwords must be configured on the server.',503);if(!await equal(expected,password))throw new AppError('NOT_AUTHORIZED','Incorrect demo password.',401);const existing=await currentUser(req);const user={userId:existing?.role===role?existing.userId:crypto.randomUUID(),role};const body=Buffer.from(JSON.stringify({...user,exp:Date.now()+7*86400000})).toString('base64url');return {user,cookie:`slotpilot_session=${body}.${await sign(body)}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800${new URL(req.url).protocol==='https:'?'; Secure':''}`}}
