import type { AppState, User, Booking, Action } from '../../contracts/app.ts';
import { RULES, PreparedActionSchema, type SlotOption } from '../../contracts/domain.ts';
import { parseToolArguments, type ToolName } from '../../contracts/tools.ts';
import { parseToolResult } from '../../contracts/tool-outputs.ts';
import { updateRequest, requireVersion, missingFields } from '../domain/requests.ts';
import { comparePreviousOption, findOptions, quoteVisit } from '../domain/scheduler.ts';
import { localParts, localToIso, overlaps } from '../domain/time.ts';
import { AppError } from './db.ts';
import { dataset, log, request, session, initialState } from './state.ts';
function ownedBooking(state:AppState,user:User,id:string){const b=state.bookings[id];if(!b||b.ownerId!==user.userId)throw new AppError('NOT_AUTHORIZED','This booking does not belong to you.',403);return b}
function ensurePart(state:AppState,o:SlotOption){if(!o.serviceIds.includes('oil-change'))return;const rule=state.parts.find(p=>p.branchId===o.branchId&&p.vehicleId===o.vehicleId);if(rule&&(!rule.availableFrom||o.date<rule.availableFrom))throw new AppError('PART_UNAVAILABLE','The demo oil filter is not available at this branch on this date. Choose another branch or date.',409)}
function validateOption(state:AppState,user:User,o:SlotOption,now:string,ignore?:string){const r=request(state,user);requireVersion(r,o.requestVersion);if(Date.parse(o.expiresAt)<=Date.parse(now))throw new AppError('OPTION_EXPIRED','This proposal has expired. Search again.',409);const d=dataset(state,now,ignore);const check=comparePreviousOption(o,r.constraints,d,now);const q=quoteVisit(r.constraints,d);if(!check.stillFits||q.totalPriceKzt!==o.totalPriceKzt||q.totalDurationMinutes!==o.totalDurationMinutes||check.newReadyAt!==o.readyAt){const busy=check.reasons.some(x=>['TECHNICIAN_BUSY','BAY_BUSY'].includes(x.code));throw new AppError(busy?'SLOT_CONFLICT':check.reasons.some(x=>x.code==='PART_UNAVAILABLE')?'PART_UNAVAILABLE':'STALE_REQUEST',check.reasons.map(x=>x.message).join(' ')||'The proposal no longer matches the visit.',409)}ensurePart(state,o)}
function prepare(state:AppState,user:User,now:string,type:Action['actionType'],o:SlotOption,booking?:Booking){const r=request(state,user);const action:Action={...PreparedActionSchema.parse({actionId:crypto.randomUUID(),requestId:r.requestId,actionType:type,requestVersion:r.requestVersion,expectedBookingVersion:booking?.bookingVersion??null,bookingId:booking?.bookingId??null,snapshot:o,createdAt:now,expiresAt:new Date(Math.min(Date.parse(now)+RULES.optionTtlSeconds*1000,type==='cancel'?Infinity:Date.parse(o.expiresAt))).toISOString()}),ownerId:user.userId,result:null};state.actions[action.actionId]=action;const {result:_result,ownerId:_owner,...prepared}=action;r.preparedAction=prepared;r.stage='awaiting_confirmation';r.stateRevision++;log(state,user,`${type}.prepared`,now,r.requestId);return {actionId:action.actionId,actionType:type,snapshot:o,expiresAt:action.expiresAt,confirmation:'Read every detail. Ask for a separate explicit confirmation. Preparation does not reserve the slot.'}}
export function executeAction(state:AppState,user:User,now:string,actionId:string,confirmationRef:string,expectedType:Action['actionType']){
 const a=state.actions[actionId];if(!a||a.ownerId!==user.userId||a.actionType!==expectedType)throw new AppError('NOT_AUTHORIZED','Unknown prepared action.',403);
 const ev=state.evidence[confirmationRef];if(!ev||ev.actionId!==actionId||ev.ownerId!==user.userId)throw new AppError('CONFIRMATION_REQUIRED','Please explicitly confirm the current proposal, using the confirmation button if needed.',409);
 // Idempotency is evaluated before expiration/current request checks, but after ownership/evidence.
 if(a.result)return a.result;
 const r=request(state,user);if(r.requestId!==a.requestId||r.requestVersion!==a.requestVersion||r.preparedAction?.actionId!==a.actionId)throw new AppError('STALE_REQUEST','The conditions or proposal changed. Review and confirm the new proposal.',409);
 if(Date.parse(a.expiresAt)<=Date.parse(now))throw new AppError('OPTION_EXPIRED','The proposal expired. Search again.',409);
 let b:Booking;
 if(a.actionType==='create'){
  if(r.bookingId)throw new AppError('REQUEST_CLOSED','This visit already has a booking.',409);validateOption(state,user,a.snapshot,now);
  const id=crypto.randomUUID();b={bookingId:id,ownerId:user.userId,requestId:r.requestId,bookingVersion:1,status:'confirmed',snapshot:a.snapshot,createdAt:now,updatedAt:now};state.bookings[id]=b;r.bookingId=id;
 }else{
  b=ownedBooking(state,user,a.bookingId!);if(b.bookingVersion!==a.expectedBookingVersion||b.status!=='confirmed')throw new AppError('STALE_BOOKING','This booking has changed. Refresh it first.',409);
  if(a.actionType==='reschedule'){validateOption(state,user,a.snapshot,now,b.bookingId);b.snapshot=a.snapshot;r.bookingId=b.bookingId}
  else b.status='cancelled';b.bookingVersion++;b.updatedAt=now;
 }
 a.result=structuredClone(b);r.stage='booked';r.stateRevision++;r.preparedAction=null;state.calendarRevision++;log(state,user,`booking.${a.actionType==='create'?'created':a.actionType==='reschedule'?'rescheduled':'cancelled'}`,now,r.requestId);return b;
}
export function confirmEvidence(state:AppState,user:User,now:string,input:{actionId:string;source:'button'|'voice';text?:string;itemId?:string}){
 const a=state.actions[input.actionId],r=request(state,user);if(!a||a.ownerId!==user.userId||r.preparedAction?.actionId!==a.actionId||r.requestVersion!==a.requestVersion)throw new AppError('STALE_REQUEST','Review the current proposal first.',409);
 if(Date.parse(a.expiresAt)<=Date.parse(now))throw new AppError('OPTION_EXPIRED','The proposal expired. Search again.',409);
 if(input.source==='voice'){
  // Entire FINAL utterance only; "yes, but add diagnostics" can never pass this allow-list.
  const normalized=(input.text??'').toLowerCase().replace(/[.!?,]/g,'').replace(/\s+/g,' ').trim();
  if(!input.itemId||!['yes','yes please','yes book it','yes please book it','confirm','i confirm','book it','please book it','yes that is correct','yes that\'s correct','yes cancel it','yes reschedule it'].includes(normalized))return {confirmationRef:null};
 }
 const ref=crypto.randomUUID();state.evidence[ref]={confirmationRef:ref,actionId:a.actionId,ownerId:user.userId,source:input.source,createdAt:now,...(input.source==='voice'?{transcript:input.text}: {})};return {confirmationRef:ref};
}
export function invalidateVoiceEvidence(state:AppState,user:User){const r=request(state,user);for(const [id,e] of Object.entries(state.evidence))if(e.ownerId===user.userId&&e.source==='voice'&&e.actionId===r.preparedAction?.actionId&&!state.actions[e.actionId]?.result)delete state.evidence[id]}
export function runTool(state:AppState,user:User,name:ToolName,raw:unknown,now:string):unknown{return parseToolResult(name,runUnchecked(state,user,name,raw,now))}
function runUnchecked(state:AppState,user:User,name:ToolName,raw:unknown,now:string):unknown{
 // Generic dispatch narrows and validates each tool independently at the boundary.
 const r=request(state,user);const d=dataset(state,now);
 if(name==='get_services'){const a=parseToolArguments(name,raw);return {services:d.services.filter(s=>!a.vehicleId||s.vehicleIds.includes(a.vehicleId)),vehicles:d.vehicles,branches:d.branches,bufferMinutes:15,currency:'KZT',demoData:true}}
 if(name==='update_request'){const a=parseToolArguments(name,raw);const old=r.options[0]??r.preparedAction?.snapshot;const next=updateRequest(r,user,a.patch,a.expectedRequestVersion);state.requests[r.requestId]=next;if(next.requestVersion!==r.requestVersion){delete state.searches[r.requestId];if(old)state.comparisons[r.requestId]=comparePreviousOption(old,next.constraints,d,now);log(state,user,'constraints.updated',now,r.requestId)}const missing=missingFields(next.constraints);if(missing.length)return {request:next,missingFields:missing};next.stateRevision++;const result=findOptions(next,d,{now,nextOptionId:()=>crypto.randomUUID()});next.options=result.options;next.preparedAction=null;next.stage=result.options.length?'offered':'collecting';state.searches[next.requestId]=result;log(state,user,'options.calculated',now,next.requestId);return {request:next,missingFields:[],search:result}}
 if(name==='find_options'){const a=parseToolArguments(name,raw);requireVersion(r,a.expectedRequestVersion);if(r.bookingId)throw new AppError('REQUEST_CLOSED','Start a new request to plan a reschedule.',409);const started=Date.now();r.stateRevision++;const result=findOptions(r,d,{now,nextOptionId:()=>crypto.randomUUID()});
  r.options=result.options;r.preparedAction=null;r.stage=result.options.length?'offered':'collecting';state.searches[r.requestId]=result;log(state,user,'options.calculated',now,r.requestId);return {...result,searchDurationMs:Date.now()-started};}
 if(name==='prepare_booking'){const a=parseToolArguments(name,raw);requireVersion(r,a.expectedRequestVersion);if(r.bookingId)throw new AppError('REQUEST_CLOSED','This request is already booked.',409);const o=r.options.find(x=>x.optionId===a.optionId);if(!o)throw new AppError('STALE_REQUEST','Select a current option.',409);validateOption(state,user,o,now);return prepare(state,user,now,'create',o)}
 if(name==='confirm_booking'||name==='reschedule_booking'||name==='cancel_booking'){const a=parseToolArguments(name,raw);return executeAction(state,user,now,a.actionId,a.confirmationRef,name==='confirm_booking'?'create':name==='cancel_booking'?'cancel':'reschedule')}
 if(name==='get_booking'){const a=parseToolArguments(name,raw);if('bookingId'in a)return ownedBooking(state,user,a.bookingId);const action=state.actions[a.actionId];if(!action||action.ownerId!==user.userId)throw new AppError('NOT_AUTHORIZED','Unknown action.',403);return action.result??{status:'not_committed',actionId:action.actionId,canRetry:Date.parse(action.expiresAt)>Date.parse(now)}}
 if(name==='prepare_change'){const a=parseToolArguments(name,raw);const b=ownedBooking(state,user,a.bookingId);if(b.status!=='confirmed'||b.bookingVersion!==a.expectedBookingVersion)throw new AppError('STALE_BOOKING','Refresh the booking before changing it.',409);if(a.changeType==='cancel')return prepare(state,user,now,'cancel',b.snapshot,b);requireVersion(r,a.expectedRequestVersion);if(r.bookingId)throw new AppError('REQUEST_CLOSED','Start a new request for rescheduling.',409);const o=r.options.find(x=>x.optionId===a.optionId);if(!o)throw new AppError('STALE_REQUEST','Find and select a current replacement time.',409);validateOption(state,user,o,now,b.bookingId);return prepare(state,user,now,'reschedule',o,b)}
 if(name==='create_callback_request'){const a=parseToolArguments(name,raw);requireVersion(r,a.expectedRequestVersion);const existing=Object.values(state.callbacks).find(c=>c.requestId===r.requestId&&c.reason===a.reason);if(existing)return existing;const c={constraints:structuredClone(r.constraints),id:crypto.randomUUID(),requestId:r.requestId,ownerId:user.userId,reason:a.reason,createdAt:now,status:'open' as const};state.callbacks[c.id]=c;log(state,user,'callback.created',now,r.requestId);return c}
 throw new AppError('VALIDATION_ERROR','Unknown tool.');
}
export function idempotentTool(state:AppState,user:User,callId:string,name:ToolName,args:unknown,now:string){const s=session(state,user);const signature=JSON.stringify({name,args});const cached=s.toolCalls[callId];if(cached){if(cached.signature!==signature)throw new AppError('VALIDATION_ERROR','This call ID was already used for different arguments.',409);return cached.result}const result=runTool(state,user,name,args,now);s.toolCalls[callId]={signature,result};const keys=Object.keys(s.toolCalls);for(const key of keys.slice(0,Math.max(0,keys.length-150)))delete s.toolCalls[key];return result}
export function demoAction(state:AppState,user:User,now:string,action:'reset'|'busy'|'occupy'|'part',optionId?:string){if(user.role!=='admin')throw new AppError('NOT_AUTHORIZED','Administrator access required.',403);
 if(action==='reset'){const fresh=initialState(now);Object.assign(state,fresh);log(state,user,'demo.reset',now);return {generation:state.generation}}
 if(action==='part'){state.parts=[{branchId:'centre',vehicleId:'sedan-petrol',availableFrom:null}];state.calendarRevision++;log(state,user,'demo.part_unavailable',now);return {partUnavailable:true}}
 if(action==='occupy'){const o=Object.values(state.requests).flatMap(r=>r.options).find(o=>o.optionId===optionId);if(!o)throw new AppError('OPTION_EXPIRED','No current option with this ID.',409);const data=dataset(state,now);if(data.reservations.some(x=>x.resourceId===o.technicianId&&overlaps(o.startAt,o.readyAt,x.startAt,x.endAt)))throw new AppError('SLOT_CONFLICT','This resource is already occupied.',409);state.extraReservations.push({id:crypto.randomUUID(),resourceId:o.technicianId,resourceKind:'technician',startAt:o.startAt,endAt:o.readyAt,status:'active'});state.calendarRevision++;log(state,user,'demo.resource_occupied',now);return {occupied:true}}
 if(action==='busy'){const date=localParts(now).date;const data=dataset(state,now);for(const t of data.technicians){const startAt=localToIso(date,t.branchId==='centre'?'15:00':'14:00'),endAt=localToIso(date,'18:00');if(Date.parse(endAt)>Date.parse(now)&&!data.reservations.some(x=>x.resourceId===t.id&&overlaps(startAt,endAt,x.startAt,x.endAt)))state.extraReservations.push({id:crypto.randomUUID(),resourceId:t.id,resourceKind:'technician',startAt,endAt,status:'active'})}state.calendarRevision++;log(state,user,'demo.busy_day',now);return {busyDate:date}}
}
