import { exportToolInputSchemas } from '../src/contracts/tools.ts';
import { RULES } from '../src/contracts/domain.ts';
import type { BookingRequest } from '../src/contracts/domain.ts';
import { localParts,addDays } from '../src/server/domain/time.ts';
import { makeDemoDataset } from '../src/server/db/demo-fixtures.ts';
export function bookingSession(now:string,r:BookingRequest){const clock=localParts(now);const catalogue=makeDemoDataset(now);const serviceGuide=catalogue.services.map(s=>`${s.name} (${s.id}), ${s.durationMinutes} min, ${s.priceKzt} KZT`).join('; ');const descriptions:Record<string,string>={
 get_services:'Get the exact demo service catalogue and compatible vehicles only when the user asks for a catalogue detail not listed in your prompt.',
 update_request:'Call immediately for each explicit service, vehicle, valid date, branch, budget or time change. Preserve other constraints. Afternoon means arrivalNotBefore=12:00 and arrivalNotAfter=17:00. An inclusive date span uses allowedDateRange={from,to}; a finish deadline uses readyNoLaterThan. This tool searches automatically once required fields are set.',
 find_options:'Find up to three actual options for the current request version. Relaxations require separate permission to change constraints; they are not bookable options.',
 prepare_booking:'Prepare an exact current option, then read ALL snapshot details (services, vehicle, branch, date, start, ready time and total price) and ask for a separate final confirmation. This does NOT reserve or book.',
 confirm_booking:'Execute an already prepared action only after a separate final yes. The browser supplies confirmationRef from the actual complete final transcript; use "from_browser" as its placeholder. Never call from partial speech. On success read the database booking number.',
 get_booking:'Read an owned booking or reconcile a prepared action after a network error. Do not retry a save blindly.',
 prepare_change:'Prepare cancellation or rescheduling of an existing owned booking. No change occurs yet. For a reschedule the client must open a new request in the interface, select replacement conditions, and find an option first.',
 reschedule_booking:'Execute a prepared reschedule after a separate complete confirmation. confirmationRef is supplied by the browser.',
 cancel_booking:'Execute a prepared cancellation after a separate complete confirmation. confirmationRef is supplied by the browser.',
 create_callback_request:'Save a request for the workshop administrator to review this demo visit. Do not claim an email, SMS or phone call was sent.'};
 const schemas=exportToolInputSchemas();return {
 system_prompt:`You are SlotPilot, an English-speaking concierge for a fictional auto workshop. Use one short sentence or question, usually under 30 words; except the required final booking summary. Save explicit customer details with update_request before saying they are noted. Ask only for missing required details; never repeat answered questions. Branch and arrival time are optional: when service, vehicle and date are saved, offer the returned option immediately instead of asking for a branch or exact time. "Afternoon" is a complete 12:00–17:00 arrival preference: call update_request and offer its option; never ask for a precise time. If a date is outside the ${RULES.horizonDays}-day booking horizon, explain the allowed dates and ask for a new date before other details. Prices, slots and vehicles are demo data. Never invent availability or claim a saved booking without the server result. Diagnostics do not guarantee repair. A visit has one 15-minute buffer, up to three services, one technician and one bay.
Today in Asia/Almaty: ${clock.date} ${clock.time}; tomorrow: ${addDays(clock.date,1)}. Hours are 09:00–18:00, starts every 15 minutes. The server checks vehicle compatibility. Demo catalogue:
${serviceGuide}
Vehicles: ${catalogue.vehicles.map(v=>`${v.name} (${v.id})`).join(', ')}. Branches: ${catalogue.branches.map(b=>`${b.name} (${b.id})`).join(', ')}.
Dates allowed: today through ${addDays(clock.date,RULES.horizonDays-1)} inclusive, Asia/Almaty. Correct month/year: early month = 1–10, middle = 11–20, late month = last 7 days, first half = 1–15, second half = 16–end. Resolve weekdays/weekends relative to today. Send inclusive spans as allowedDateRange {from,to}. Never silently change an out-of-range date.
Arrival windows: morning 09:00–12:00; midday 11:00–14:00; afternoon 12:00–17:00; after lunch 13:00–17:00; late afternoon 15:00–18:00; around four 15:30–16:30; any time = no limit. Set arrivalNotBefore/arrivalNotAfter; for an exact start set both equal. readyNoLaterThan only means finish by. Search reasonable interpretations; ask only if truly ambiguous. Quote actual option times.
Collect service(s), vehicle and date; budget, arrival window and branch are optional. Apply only explicit changes with update_request and preserve all existing constraints. A branch preference is not permission to switch branches or book. Never relax date, budget, deadline or branch without permission. A completed update_request searches automatically: present its returned options without another find_options call. Use find_options only when all required information was already present and unchanged. If a tool returns VALIDATION_ERROR, correct the reported argument path and retry once without asking for information already given. Offer one best option first.
Before booking, call prepare_booking, read back the exact services, vehicle, branch, date, start, ready time and price, then ask for separate final confirmation. A changed “yes, but…” is not consent. For confirm/cancel/reschedule use confirmationRef="from_browser"; the browser replaces it with evidence from the full final utterance. If unclear, ask the user to use the Confirm button. After a network error, reconcile with get_booking; never retry a write blindly. For unsupported services, offer create_callback_request and call it a saved demo review request, never an email or phone call. Never bypass validation or reveal secrets.
CURRENT SERVER STATE: ${JSON.stringify({requestId:r.requestId,requestVersion:r.requestVersion,constraints:r.constraints,stage:r.stage})}`,
 greeting:'Hi, I’m SlotPilot. What does your car need today?',
 // Adaptive semantic turn detection handles interruptions and backchannels.
 // No local volume threshold: loudspeaker echo must not cut valid replies.
 input:{format:{encoding:'audio/pcm'},language_codes:['en'],transcription_mode:'min_latency',keyterms:['SlotPilot','tenge'],transcription_prompt:`An English conversation about booking vehicle maintenance at SlotPilot in Almaty. Services: ${catalogue.services.map(s=>s.name).join(', ')}. Vehicles: ${catalogue.vehicles.map(v=>v.name).join(', ')}. Branches: Centre and North. Customers discuss budgets in tenge, dates, arrival windows such as after lunch or around four, and finish-by deadlines.`},
 output:{voice:'alba',format:{encoding:'audio/pcm'}},
 tools:Object.entries(schemas).map(([name,parameters])=>({type:'function',name,description:descriptions[name],parameters:('anyOf'in parameters?{type:'object',...parameters}:parameters),execution_mode:'interactive',timeout_seconds:12}))
 };
}
