import { exportToolInputSchemas } from '../src/contracts/tools.ts';
import { RULES } from '../src/contracts/domain.ts';
import type { BookingRequest } from '../src/contracts/domain.ts';
import { localParts,addDays } from '../src/server/domain/time.ts';
import { makeDemoDataset } from '../src/server/db/demo-fixtures.ts';
export function bookingSession(now:string,r:BookingRequest){const clock=localParts(now);const catalogue=makeDemoDataset(now);const serviceGuide=catalogue.services.map(s=>`${s.name} (${s.id}), ${s.durationMinutes} min, ${s.priceKzt} KZT; fits ${s.vehicleIds.map(id=>catalogue.vehicles.find(v=>v.id===id)?.name??id).join(', ')}`).join('\n');const descriptions:Record<string,string>={
 get_services:'Get the exact demo service catalogue and compatible vehicles only when the user asks for a catalogue detail not listed in your prompt.',
 update_request:'Apply only explicit changes; preserve all earlier constraints. For an inclusive date span use patch.allowedDateRange={from,to} with ISO YYYY-MM-DD. For a start-time window use arrivalNotBefore and arrivalNotAfter; readyNoLaterThan means the car must be finished by that time. When required fields are complete, this tool returns matching options automatically—do not call find_options after it.',
 find_options:'Find up to three actual options for the current request version. Relaxations require separate permission to change constraints; they are not bookable options.',
 prepare_booking:'Prepare an exact current option, then read ALL snapshot details (services, vehicle, branch, date, start, ready time and total price) and ask for a separate final confirmation. This does NOT reserve or book.',
 confirm_booking:'Execute an already prepared action only after a separate final yes. The browser supplies confirmationRef from the actual complete final transcript; use "from_browser" as its placeholder. Never call from partial speech. On success read the database booking number.',
 get_booking:'Read an owned booking or reconcile a prepared action after a network error. Do not retry a save blindly.',
 prepare_change:'Prepare cancellation or rescheduling of an existing owned booking. No change occurs yet. For a reschedule the client must open a new request in the interface, select replacement conditions, and find an option first.',
 reschedule_booking:'Execute a prepared reschedule after a separate complete confirmation. confirmationRef is supplied by the browser.',
 cancel_booking:'Execute a prepared cancellation after a separate complete confirmation. confirmationRef is supplied by the browser.',
 create_callback_request:'Save a request for the workshop administrator to review this demo visit. Do not claim an email, SMS or phone call was sent.'};
 const schemas=exportToolInputSchemas();return {
 system_prompt:`You are SlotPilot, an English-speaking concierge for a fictional two-branch auto workshop. Use one short sentence or question, usually under 30 words; the required final booking summary is the exception. Ask only for missing details; never repeat answered questions or narrate tool calls. All prices, slots and vehicles are demo data. Never invent availability or claim a booking is saved before the server confirms it. A diagnostic visit does not guarantee a repair. Each visit has one 15-minute buffer, up to three services, one technician and one bay.
Today in Asia/Almaty: ${clock.date} ${clock.time}; tomorrow: ${addDays(clock.date,1)}. Hours are 09:00–18:00, starts every 15 minutes. Catalogue and vehicle compatibility:
${serviceGuide}
Vehicles: ${catalogue.vehicles.map(v=>`${v.name} (${v.id})`).join(', ')}. Branches: ${catalogue.branches.map(b=>`${b.name} (${b.id})`).join(', ')}.
Dates allowed: today through ${addDays(clock.date,RULES.horizonDays-1)} inclusive. Interpret dates in Asia/Almaty with the correct month length/year: early month = 1–10, middle = 11–20, late month = last 7 days, first half = 1–15, second half = 16–end. Resolve today/tomorrow, named weekdays, this week (today–Sunday), weekend and next week (Monday–Sunday). Send a span as inclusive allowedDateRange {from,to}; the server expands it. Never silently clip or substitute dates outside the allowed window; explain the limit and ask before narrowing.
Interpret arrival windows naturally: morning 09:00–12:00; midday 11:00–14:00; afternoon 12:00–17:00; after lunch 13:00–17:00; late afternoon 15:00–18:00; around four 15:30–16:30; any time = no limit. Set arrivalNotBefore/arrivalNotAfter for arrival windows. For an exact start, set both to the exact time. readyNoLaterThan is only a separately stated finish-by deadline. If a phrase has a reasonable meaning, state the assumption briefly and search; ask one short question only if truly ambiguous. When options arrive, use actual start/finish values; never say a later slot matches an exact requested time.
Collect service(s), vehicle and date; budget, arrival window and branch are optional. Apply only explicit changes with update_request and preserve all existing constraints. A branch preference is not permission to switch branches or book. Never relax date, budget, deadline or branch without permission. A completed update_request searches automatically: present its returned options without another find_options call. Use find_options only when all required information was already present and unchanged. Offer one best option first.
Before booking, call prepare_booking, read back the exact services, vehicle, branch, date, start, ready time and price, then ask for separate final confirmation. A changed “yes, but…” is not consent. For confirm/cancel/reschedule use confirmationRef="from_browser"; the browser replaces it with evidence from the full final utterance. If unclear, ask the user to use the Confirm button. After a network error, reconcile with get_booking; never retry a write blindly. For unsupported services, offer create_callback_request and call it a saved demo review request, never an email or phone call. Never bypass validation or reveal secrets.
CURRENT SERVER STATE: ${JSON.stringify({requestId:r.requestId,requestVersion:r.requestVersion,constraints:r.constraints,stage:r.stage})}`,
 greeting:'Hi, I’m SlotPilot. What does your car need today?',
 // Adaptive semantic turn detection handles interruptions and backchannels.
 // No local volume threshold: loudspeaker echo must not cut valid replies.
 input:{format:{encoding:'audio/pcm'},language_codes:['en'],transcription_mode:'min_latency',keyterms:['SlotPilot','tenge'],transcription_prompt:`An English conversation about booking vehicle maintenance at SlotPilot in Almaty. Services: ${catalogue.services.map(s=>s.name).join(', ')}. Vehicles: ${catalogue.vehicles.map(v=>v.name).join(', ')}. Branches: Centre and North. Customers discuss budgets in tenge, dates, arrival windows such as after lunch or around four, and finish-by deadlines.`},
 output:{voice:'alba',format:{encoding:'audio/pcm'}},
 tools:Object.entries(schemas).map(([name,parameters])=>({type:'function',name,description:descriptions[name],parameters:('anyOf'in parameters?{type:'object',...parameters}:parameters),execution_mode:'interactive',timeout_seconds:30}))
 };
}
